### ISSUE TITLE
Is this expected to work on OS X?

### ISSUE THREAD

**Issue by martijnthe** [sandeepmistry/node-bluetooth-hci-socket#19]
I noticed:

> NOTE: Currently only supports Linux and Windows.

but also at the end of the page there are some notes about disabling the Bluetooth kexts on OS X.

So is this expected to work on OS X?

This returns `-1` for me (after disabling all Bluetooth kexts):
```
socket(31, SOCK_RAW, 1);
```
I also tried 36 instead of 31, same deal.

**Comment by sandeepmistry** [comment]
@martijnthe 

> So is this expected to work on OS X?

Only the USB binding, not the native code. Because OS X has no concept for Bluetooth kernel sockets. The instructions in the read me are to unload the built-in USB Bluetooth drivers. Then node-usb can talk to the adapter directly.

See: https://github.com/sandeepmistry/node-bluetooth-hci-socket/blob/master/lib/usb.js
